# Site settings
title: The Adventures of Cio
description: The journey of Cio in Tech's World
url: 'http://duytran.github.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Duy Tran'
  email: tranduydn@gmail.com
  twitter_username: ciosanza
  facebook_username: tranduy
  github_username:  duytran
  linkedin_username:  duy-tran-89078433

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
